hero_image: images/banner.png
listed: false
ingredient: false
copyedit: false
title: Snowball fight
description: Make a game in which you have to throw snowballs at a target
version: 4
last_tested: 2018-04-11
steps: 
- title: Introduction
- title: Making a snowball
- title: Throwing a snowball
- title: Realistic movement
- title: The target
- title: "Challenge: improve your game!"
  challenge: true